### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by alxbar** [explosion/sense2vec#19]
when I try to install via `pip install -e git+git://github.com/spacy-io/sense2vec.git#egg=sense2vec`
or via `pip install sense2vec`, I get following error message

```
>>> import sense2vec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/anaconda2/lib/python2.7/site-packages/sense2vec/__init__.py", line 2, in <module>
    from .vectors import VectorMap
ImportError: /home/alex/anaconda2/lib/python2.7/site-packages/sense2vec/vectors.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E
```

I am using ubuntu 16.04 and python 2.7 with anaconda 4.2.9. (installed requirements-all.txt)
the problem did not occur on a mac sierra 10.12.1

**Comment by TiesdeKok** [comment]
I actually get a similar error but when trying to use `SpaCy`:

`ImportError: /home/ties/anaconda3/lib/python3.5/site-packages/spacy/tokenizer.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E`

I am also using ubuntu 16.04 but with Python 3.5 (Anaconda). 

Have you figured out how to solve it?

**Comment by TiesdeKok** [comment]
After a bit of Googling I found the answer, it has to do with the version of `libgcc` in the Anaconda environment.

The error is solved after running `conda install libgcc` in the anaconda environment.

**Comment by alxbar** [comment]
For me it just suddenly started working, I think I eventually have installed libgcc.

Yes I tried it also on my other PC (same setup same problem) and `conda install libgcc` solved the issue

**Comment by atremblay** [comment]
I have the same problem even with libgcc. Created a new env with conda 

`conda create -n spacy python=3.5 ipython`

and then install spacy (1.6.0) with pip (conda still has version 0.101.0)

`pip install spacy`

But I still get this error.

`In [1]: import spacy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c080f6458562> in <module>()
----> 1 import spacy

/home/alexis/anaconda3/envs/spacy/lib/python3.5/site-packages/spacy/__init__.py in <module>()
      4 from .about import __version__
      5
----> 6 from . import en
      7 from . import de
      8 from . import zh

/home/alexis/anaconda3/envs/spacy/lib/python3.5/site-packages/spacy/en/__init__.py in <module>()
      6 from ..util import match_best_version
      7 from ..util import get_data_path
----> 8 from ..language import Language
      9 from ..lemmatizer import Lemmatizer
     10 from ..vocab import Vocab

/home/alexis/anaconda3/envs/spacy/lib/python3.5/site-packages/spacy/language.py in <module>()
     15
     16
---> 17 from .tokenizer import Tokenizer
     18 from .vocab import Vocab
     19 from .tagger import Tagger

ImportError: /home/alexis/anaconda3/envs/spacy/lib/python3.5/site-packages/spacy/tokenizer.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTINSt8ios_base7failureB5cxx11E`
